name: Continuous Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-to-production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # ===============================================
      # 1. CHECKOUT ET SETUP
      # ===============================================
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ===============================================
      # 2. BUILD APPLICATION
      # ===============================================
      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      # ===============================================
      # 3. CONFIGURATION ENVIRONNEMENT
      # ===============================================
      - name: Set environment variables
        run: |
          SERVICE_NAME="ptk-products-api"
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
          echo "ENVIRONMENT=production" >> $GITHUB_ENV

          echo "Service: $SERVICE_NAME"
          echo "Environment: production"
          echo "SHA: $(echo ${{ github.sha }} | cut -c1-8)"

      # ===============================================
      # 4. BUILD ET PUSH DOCKER IMAGE
      # ===============================================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}"
          
          TAG_PROD="production"
          TAG_SHA="production-${{ env.SHORT_SHA }}"
          TAG_DATE="production-${{ env.DATE_TAG }}"
          TAG_LATEST="production-latest"

          echo "Building image: $IMAGE_NAME"
          echo "Tags: $TAG_PROD, $TAG_SHA, $TAG_DATE, $TAG_LATEST"

          docker build -t $IMAGE_NAME:$TAG_PROD .

          docker tag $IMAGE_NAME:$TAG_PROD $IMAGE_NAME:$TAG_SHA
          docker tag $IMAGE_NAME:$TAG_PROD $IMAGE_NAME:$TAG_DATE
          docker tag $IMAGE_NAME:$TAG_PROD $IMAGE_NAME:$TAG_LATEST

          docker push $IMAGE_NAME:$TAG_PROD
          docker push $IMAGE_NAME:$TAG_SHA
          docker push $IMAGE_NAME:$TAG_DATE
          docker push $IMAGE_NAME:$TAG_LATEST

          echo "✅ Image pushed successfully: $IMAGE_NAME:$TAG_PROD"

      # ===============================================
      # 5. AUTHENTIFICATION GCP
      # ===============================================
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # ===============================================
      # 6. DÉPLOIEMENT SUR VM GCP
      # ===============================================
      - name: Deploy to GCP VM Production
        run: |
          cat > deploy-script.sh << 'EOF'
          #!/bin/bash
          set -e

          SERVICE_NAME="${{ env.SERVICE_NAME }}"
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          IMAGE_TAG="production-${{ env.SHORT_SHA }}"

          echo "Deploying $SERVICE_NAME to PRODUCTION"
          echo "Image: $DOCKER_USERNAME/$SERVICE_NAME:$IMAGE_TAG"

          cd /opt/payetonkawa

          echo "Pulling new image..."
          sudo docker pull $DOCKER_USERNAME/$SERVICE_NAME:$IMAGE_TAG

          COMPOSE_SERVICE="products-api-prod"

          echo "Restarting service: $COMPOSE_SERVICE"

          sudo sed -i "s|DOCKER_REGISTRY=.*|DOCKER_REGISTRY=$DOCKER_USERNAME|g" .env

          sudo docker-compose stop $COMPOSE_SERVICE || true
          sudo docker-compose rm -f $COMPOSE_SERVICE || true

          sudo docker-compose up -d $COMPOSE_SERVICE

          echo "Waiting for service to be ready..."
          sleep 30

          HEALTH_PORT="4003"

          echo "Health check on port $HEALTH_PORT"

          for i in {1..5}; do
            if curl -f http://localhost:$HEALTH_PORT/health 2>/dev/null; then
              echo "✅ Service $COMPOSE_SERVICE is healthy"
              break
            elif [ $i -eq 5 ]; then
              echo "❌ Health check failed, service might still be starting"
              echo "Container status:"
              sudo docker ps | grep $COMPOSE_SERVICE || echo "Container not found"
              sudo docker-compose logs --tail=20 $COMPOSE_SERVICE || echo "No logs available"
            else
              echo "Attempt $i/5 failed, retrying in 10 seconds..."
              sleep 10
            fi
          done

          echo "Cleaning old images..."
          sudo docker images $DOCKER_USERNAME/$SERVICE_NAME --format "table {{.Tag}}\t{{.CreatedAt}}" | grep -v TAG | sort -k2 -r | tail -n +6 | awk '{print "'$DOCKER_USERNAME'/'$SERVICE_NAME':"$1}' | xargs -r sudo docker rmi || true

          echo "✅ Production deployment completed successfully"
          EOF

          chmod +x deploy-script.sh

          echo "Connecting to VM ${{ secrets.GCP_VM_NAME }}..."

          gcloud compute scp deploy-script.sh ${{ secrets.GCP_VM_NAME }}:/tmp/ \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="chmod +x /tmp/deploy-script.sh && /tmp/deploy-script.sh"

      # ===============================================
      # 7. NOTIFICATIONS
      # ===============================================
      - name: Deployment success notification
        if: success()
        run: |
          echo "✅ Production deployment successful"
          echo "Service: ${{ env.SERVICE_NAME }}"
          echo "Environment: PRODUCTION"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:production-${{ env.SHORT_SHA }}"
          echo "API URL: http://${{ secrets.VM_EXTERNAL_IP }}:4003/health"

      - name: Deployment failure notification
        if: failure()
        run: |
          echo "❌ Production deployment failed"
          echo "Service: ${{ env.SERVICE_NAME }}"
          echo "Environment: PRODUCTION"
          echo "Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"